<?php

    $genders = [1=>'Masculino', 2=>'Femenino'];

?>
<div class="card bg-secondary">
    <div class="card-header">
        <div class="card-title">Customer::Customer</div>
    </div>
    <div class="card-body">
        <form action="">
            <div class="form-group row">
                <label for="name" class="col-form-label col-4">
                    Primer Nombre
                </label>
                <div class="col-4">
                    <input name="name" type="text" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="middleName" class="col-form-label col-4">
                    Segundo Nombre
                </label>
                <div class="col-4">
                    <input name="middleName" type="text" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="lastName" class="col-form-label col-4">Apellido Paterno</label>
                <div class="col-4">
                    <input name="lastName" type="text" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="secondLastName" class="col-form-label col-4"></label>
                <div class="col-4">
                    <input name="secondLastName" type="text" class="form-control">
                </div>
            </div>

            <div class="form-group row">
                <label for="gender" class="col-form-label col-4"></label>
                <div class="col-4">
                    <select name="gender" class="form-control">
                        <option value="0" disabled selected>Seleccione opcion</option>
                        <?php foreach ($genders as $i => $gender) : ?>
                            <option value="<?= $i ?>">
                                <?= $gender ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </form>
    </div>
</div>